import os
import Display as display

def main_menu():
    os.system('cls')
    print(display.welcome_menu())
    print("1. Sign In")
    print("2. Exit")
    return input("Choose an option: ")

def super_admin_menu():
    os.system('cls')
    print(display.super_admin_menu())
    print("1. Update password")
    print("2. View users")
    print("3. Member management")
    print("   Add member")
    print("   Edit member")
    print("   Delete member")
    print("   View members")
    print("   Search members")
    print("4. Consultant management")
    print("   Add Consultant")
    print("   Edit Consultant")
    print("   Delete Consultant")
    print("   Reset consultant password (temporary)")
    print("5. System Admin management")
    print("   Add System Admin")
    print("   Edit System Admin")
    print("   Delete System Admin")
    print("   Reset System admin password (temporary)")
    print("6. Backup and Restore")
    print("   Create backup")
    print("   Restore backup")
    print("7. View logs")
    print("8. Exit")
    return input("Choose an option: ")



def system_admin_menu():
    os.system('cls')
    print(display.system_admin_menu())
    print("1. Update password")
    print("2. View users")
    print("3. Member management")
    print("   Add member")
    print("   Edit member")
    print("   Delete member")
    print("   View members")
    print("   Search members")
    print("4. Consultant management")
    print("   Add Consultant")
    print("   Edit Consultant")
    print("   Delete Consultant")
    print("   Reset consultant password (temporary)")
    print("5. Backup and Restore")
    print("   Create backup")
    print("   Restore backup")
    print("6. View logs")
    print("7. Exit")
    return input("Choose an option: ")

def consultant_menu():
    os.system('cls')
    print(display.consultant_menu())
    print("1. Update password")
    print("2. Add member")
    print("3. Edit member")
    print("4. Search member")
    print("5. Exit")
    return input("Choose an option: ")

def default_menu():
    os.system('cls')
    print("\nDefault Menu")
    print("1. View profile")
    print("2. Update profile")
    print("3. Exit")
    return input("Choose an option: ")